Exposing Camera Euler Angles
olexale/arkit_flutter_plugin pull request #119
Opened 2020-12-20 21:41 UTC by devsherif

For an app I am developing. I needed to position a 2D plane and rotate it initially to face the camera.
That's why I needed to access Camera's EulerAngles and I had to expose it using native Swift method.

I hope my change is clean enough for being merged with your main repo.

Thanks,

2020-12-25 19:45 UTC, olexale commented
Hi @devsherif ,

Thank you for your contribution! 👍🏻

Please fix the comments above and I'll be glad to merge your changes to the repo!
Thanks in advance!

Kind regards,
Oleksandr

2020-12-25 19:45 UTC, olexale requested changes

2020-12-25 19:45 UTC, olexale commented on ios/Classes/FlutterArkitView+Handlers.swift
> +            let res = serializeVector(point)
I propose to create an instance of `SCNVector3` and call `serializeVector()` on it.

2020-12-25 19:45 UTC, olexale commented on lib/widget/arkit_scene_view.dart
> +  Future<Vector3> _getCameraEulerAngles() async{
Shouldn't this method be public?

2020-12-25 19:45 UTC, olexale commented on lib/widget/arkit_scene_view.dart
> +    var vector3 = _vector3Converter.fromJson(result);
please make it `final` as well.

2020-12-26 15:34 UTC, devsherif commented
Hi @olexale ,

Thanks for your attention. 
Requested changes applied. Please check.

Regards,
Sherif

2021-01-07 09:41 UTC, merged

2021-01-07 09:42 UTC, olexale commented
Hi @devsherif! 

I'll push a new version with your changes today. 
Thanks for your help!!

Kind regards,
Oleksandr

2021-01-09 07:06 UTC, devsherif commented
Hi @olexale ,

Thanks a lot for your attention. 
And you can expect more changes soon ;)

Regards,
Sherif

2021-12-23 09:29 UTC, benMOOVENCY commented
Hi @devsherif, 

have you a solution to expose the quaternion instead of the Euler angle to avoid the gimbal lock.

Cheers